# SELECT timestamp '2005-10-10 05:16:45';
#
# SELECT NOW();
#
# SELECT TO_CHAT(NOW(), 'DD');
# SELECT TO_CHAT(NOW(), 'DD-MM-YYYY');
# SELECT TO_CHAT(NOW(), 'DD-MM-YYYY HH:MI:SEC');
# SELECT TO_CHAT(NOW(), 'Day, DD-MM-YYYY HH:MI:SEC');
# SELECT TO_CHAT(NOW(), 'FMDay, DD-MM-YYYY HH:MI:SEC');
# SELECT TO_CHAT(NOW(), 'FMDay, Month DD-MM-YYYY HH:MI:SEC');
# SELECT TO_CHAT(NOW(), 'FMDay, FMMonth DD-MM-YYYY HH:MI:SEC');
# SELECT TO_CHAT(NOW(), 'FMDay, DDth, FMMonth, YYYY HH:MI:SEC');
#
# SELECT TO_TIMESTAMP('Saturday 21st May, 2016 06:19:11', 'FMDay, DDth, FMMonth, YYYY HH:MI:SEC');
